### ISSUE TITLE
docker-compose yml example ? 

### ISSUE THREAD

**Issue by silkyclouds** [xataz/docker-rtorrent-rutorrent#13]
Hi there,

Would some nice person post a yml file in order to let me install this using docker-compose ? 

that would be really nice ! 

Thanks !

**Comment by PixiBixi** [comment]
You have a nice docker example here : https://github.com/xataz/docker-rtorrent-rutorrent#advanced-launch

Do you really need a docker-compose.yml example, can you adapt-it yourself.. ?

**Comment by silkyclouds** [comment]
Hi Jérémy,

thanks for answering ! (Based on your name, I believe we might want to continue this discussion in French?)

First of all let me explain to you how all my different apps currently works. 

each of my apps are hosted in a different container and a specific vhost has been created in nginx to enable them behind a reverse proxy. 

I run nginx to listen to port 80 + redirect all traffic to port 443 to force all my apps to run exclusively in https, and listen to my apps who are only reachable on localhost:port. 

if I take jackett as an example, the docker compose looks like this : 

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '127.0.0.1:9117:9117'
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - './jackett:/config'
      - '/home/plexuser/downloads:/downloads'
      - '/etc/localtime:/etc/localtime:ro'

jackett is therefore only reachable through my localhost, and nginx is reverse proxying it like this :


server {
        listen [::]:443 ssl;
        listen 443 ssl;
        server_name jackett.mydomain.com;
        location / {
                proxy_pass http://127.0.0.1:9117;
                #Next three lines allow websockets
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot

}

This works very well for all my different apps. But I’m a little struggling as I have to configure ports for both rtorrent and rutorrent this time… 

As for now, My docker-compose yml content looks like this for the rtorrent service : 

  rtorrent:
    image: xataz/rtorrent-rutorrent
    container_name: rtorrent
    restart: always
    network_mode: "bridge"
    tty: true
    ports:
      - '127.0.0.1:45000:45000'
      - '127.0.0.1:3001:3001'
    environment:
      - UID=1001
      - GID=1001
    volumes:
      - '/home/plexuser/downloads:/data’
      - '.rtorrent:/config’


So what I'm trying to reach here is the right yml in order to make it work in my current setup. 
FYI, I’ve already created the nginx reverse proxy entry like this : 

server {
        listen [::]:443 ssl;
        listen 443 ssl;
        server_name rtorrent.mydomain.com;
        location / {
                proxy_pass http://127.0.0.1:3001;
                #Next three lines allow websockets
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot

}


Port 3001 can of course be changed to anything else…I don’t care ;) 

Could you help me adapt my rtorrent section in my yml file ? :/ 

thanks again !!!

**Comment by PixiBixi** [comment]
You must use 8080 to reach your ruTorrent interface, well : 
```
    - '127.0.0.1:8080:8080'
```

And 

```
proxy_pass http://127.0.0.1:8080;
```

**Comment by silkyclouds** [comment]
Oh yes ! I did change my yml to :

rtorrent:
    image: xataz/rtorrent-rutorrent
    container_name: rtorrent
    restart: always
    network_mode: "bridge"
    tty: true
    ports:
      - '127.0.0.1:45000:45000'
      - '127.0.0.1:8080:8080'
    environment:
      - UID=1001
      - GID=1001
      - TZ=Europe/Paris
    volumes:
      - './rtorrent:/config'
      - '/home/plexuser/downloads:/data’

and now I finally see rutorrent UI running ! thanks for that ! 

But now rutorrent still isn’t connected to the rtorrent running inside the container. I’m getting a bad response from server message. Bad response from server: (0 [error,list])


What am I supposed to do to fix this ? I see you did put a lot of ports in your run container example, therefore i’m a little bit confused (this is my first rtorrent/rutorrent install) :/ 

Thanks again !! I’m almost there ;)

**Comment by silkyclouds** [comment]
Hi there,

I’ve edited my yml file which now looks like this : 

  rtorrent:
    image: xataz/rtorrent-rutorrent
    container_name: rtorrent
    restart: always
    network_mode: "bridge"
    tty: true
    ports:
      - '127.0.0.1:45000:45000'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:6881:6881'
      - '127.0.0.1:5000:5000'
    environment:
      - UID=1001
      - GID=1001
      - TZ=Europe/Paris
    volumes:
      - './rtorrent:/config'
      - '/home/plexuser/downloads:/data'

Rutorrent is reachable, and connectes to Rtorrent. When I add a torrent file, it starts downloading the file. But I still get bad response from server errors, and it seems like files are not seeding after completion of the download. I see 0 peers connected. 

Any idea what this could come from ? 

Thanks again !

**Comment by silkyclouds** [comment]
FYI no error when logging in (so I guess rtorrent connexion is all set) , but after that, lots of different different errors :

**Comment by silkyclouds** [comment]
Hey there,

Just a litle update to let you know that opening listening ports helped me getting rid of the errors ;) 

So I seem to be all set for now. 

One more thing, how can I test if filebot is working ? 

Best,

Me

**Comment by PixiBixi** [comment]
Lol, it cant works without the :filebot tag :-) (rtorrent-rutorrent:filebot)

Envoyé de mon iPhone

Le 7 mai 2018 à 14:11, silkyclouds <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hey there,

Just a litle update to let you know that opening listening ports helped me getting rid of the errors ;)

So I seem to be all set for now.

One more thing, how can I test if filebot is working ?

Best,

Me

**Comment by silkyclouds** [comment]
AH. So I’m gonna change this 

> image: xataz/rtorrent-rutorrent 

to this 

> image: xataz/rtorrent-rutorrent:filebot

and give it another shot ;) 

Thanks !

**Comment by silkyclouds** [comment]
Hey there,

I’ve changed to rtorrent-rutorrent:filebot but still can’t see any filebot option in the rutorrent if. 

I’m also getting a crazy load of errors 



last but not least, I’ve mapped my volumes like that : 

    volumes:
      - './rtorrent:/config'
      - '/home/plexuser/downloads:/data'

rotrrent downloads files without any issue in /data/torrents, but can’t see any of the files that has been downloaded. Same issue with other content at the root of my downloads folder. As an example, I can NOT define I want to enable /data/watchfolder as my watchfolder. 

any clue what I can do to fi all this ? :/ 

Thanks !

**Comment by JustasStankunas** [comment]
Hello,
Not sure if this helps but here is torrent part from my yml file:

```
  torrent:
    image: xataz/rtorrent-rutorrent:latest-filebot                          
    restart: unless-stopped
    container_name: torrent
    volumes:
      - /mnt/md0/system/containers/mediaserver/torrent/config:/config
      - /mnt/md0/system/containers/mediaserver/torrent/data:/data
      - /mnt/md0/media-library:/data/Media
    environment:
      FILEBOT_RENAME_METHOD: duplicate
      WEBROOT: "/torrent"
      FILEBOT_RENAME_MOVIES: "{n} ({y})/{n}"                                 
      FILEBOT_RENAME_SERIES: "{n}/Season {s.pad(2)}/{n} - {s00e00} - {t$      
      UID: 1005
      GID: 10000
    ports:
      - "192.168.11.101:8080:8080"
```
I have other services exposing only ports and have but for some reason i have to map ip for torrent one (don't remember why now). And i am also reverse proxying everyting, just without SSL.

**Comment by silkyclouds** [comment]
thanks for your help Justas ! 

Unfortunately it doesn’t solve my issues. :( 

When adding the FILEBOT params in environment I get these errors : 

ERROR: Invalid interpolation format for "environment" option in service "rtorrent": "FILEBOT_RENAME_SERIES="{n}/Season {s.pad(2)}/{n} - {s00e00} - {t$”"

Regarding the volumes, rtorrent do see and create the config files without any issue.
rtorrent downloads in /data/torrents without any issue. 
in file manager, I can see the content of /data/torrents but for some reason, I can not browse to the upper folder which contains my watchfolder. 
I’m also not able to move my files manually by selecting any other folder. This is really strange. 

In the end, my only wish is to : 

1. download the file in my /data/torrent folder
2. once downloaded, filebot renames and COPIES the renamed file to my movie / serie location which is located on another drive /medias/Plex/movies and /medias/Plex/series
3. the downloaded torrent stays in its initial location /data/torrents and keeps seeding

no rocket science but for some reasons i’m stuck… :/

**Comment by JustasStankunas** [comment]
@silkyclouds 
first of  all let me say that what i have copy pasted it was little bit cropped (i did that on mobile) and *FILEBOT_RENAME_SERIES* was incorrect.. correctly pasted config is below.

second of that. this container will move or copy (duplicate) your media to /data/Media inside it. so what ever you will map to this directory media will be placed there (i am mounting there already existing media directory on my server *- /mnt/md0/media-library:/data/Media*)
to have your media duplicated or moved is decided by env variable **FILEBOT_RENAME_METHOD** (i have it set to copy media files for same reason as you: *FILEBOT_RENAME_METHOD: duplicate*)
then there is **FILEBOT_RENAME_MOVIES** & **FILEBOT_RENAME_SERIES** to define your naming standard (if you want to change this part you should follow standard filebot configuration for this part (all variables and options are listed there)

and **WEBROOT** i am using to make it easier to reverse proxy web UI.
and lastly i am not using watch folder, sonarr / radarr (maybe other soft can communicate directly with torrent) or if i want to add something manually, most likely i am doing that from mobile, so i have *transdrone* configured for this part.

```
 torrent:
    image: xataz/rtorrent-rutorrent:latest-filebot                          
    restart: unless-stopped
    container_name: torrent
    volumes:
      - /mnt/md0/system/containers/mediaserver/torrent/config:/config
      - /mnt/md0/system/containers/mediaserver/torrent/data:/data
      - /mnt/md0/media-library:/data/Media
    environment:
      FILEBOT_RENAME_METHOD: duplicate
      WEBROOT: "/torrent"
      FILEBOT_RENAME_MOVIES: "{n} ({y})/{n}"                                 
      FILEBOT_RENAME_SERIES: "{n}/Season {s.pad(2)}/{n} - {s00e00} - {t}"
      UID: 1005
      GID: 10000
    ports:
      - "192.168.11.101:8080:8080"
```
