### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by silkyclouds** [xataz/docker-rtorrent-rutorrent#24]
SAlut Xataz,

Je vois que t'as ajouté un param pour ne pas systématiquement ré-appliquer les perms. Un grand merci! 

Par contre le fichier startup ne se trouve pas dans le dossier mount en tant que /config non ? 

Donc obligé de lancer un batch dans le container et de changer ça par la ? Donc ce n'est pas permanent et ça doit être refait chaque fois qu'on pull une nouvelle version de ton docker ?

**Comment by Magicalex** [comment]
Faut activer l'option avec les variables d'environnement `env`

Exemple : mon docker-compose

```yaml
rtorrent-rutorrent:
  container_name: rtorrent-rutorrent
  restart: always
  image: xataz/rtorrent-rutorrent:latest
  networks:
    - seedbox
  environment:
    - UID=1000
    - GID=1000
    - WEBROOT=/
    - PORT_RTORRENT=45000
    - DISABLE_PERM_DATA=true
  ports:
    - 45000:45000
  volumes:
    - /home/user:/data
    - /mnt/docker/rtorrent-rutorrent:/config
```
